spring:
  application:
    name: thunder-light-upload-file-ldap

jwt:
  timeout: 10
  token-string:
    username: username
    password: password
    header: Authorization
    prefix: Bearer

  secret: asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4

ldap:
  url: ldap://DC-th01.TLS.IR
  port: 389
  directory:
    root: dc=TSL,dc=ir
  domain: TLS
  user:
    base: ou=persons,ou=people,ou=users
    filter: uid={0}
  group:
    base: ou=persons,ou=people,ou=users,dc=TSL,dc=ir
  factory: com.sun.jndi.ldap.LdapCtxFactory
  security:
    authentication: simple